theme: jekyll-theme-prologue

plugins:
  - jekyll-gallery-generator

title: MACULAN - ZAUBERER & HUMORIST
description: MACULAN - Zauberer & Humorist aus Wallsee in Nieder√∂sterreich
url: maculan.github.io
author:
  name: Johann Wieser
  email: maculan@gmx.at

paginate: 3
owner: Johann wieser
year: 2019
