plugins:
  - jekyll-gallery-generator

title: MACULAN - Zauberer & Humorist
description: MACULAN - Zauberer & Humorist aus Wallsee in Nieder√∂sterreich
url: maculan.github.io
author:
  name: Johann Wieser
  email: maculan@gmx.at

paginate: 3
owner: Johann wieser
year: 2019


# The following settings are NECESSARY for the Prologue theme to run:
#remote_theme: chrisbobbe/jekyll-theme-prologue
theme: jekyll-theme-prologue
collections: [sections]

url: "https://maculan.github.io"
base_url: "/"
avatar: /assets/images/logo.png
